### ISSUE TITLE
User experience improvements for partners

### ISSUE THREAD

**Issue by lettergram** [lettergram/vocalvoters.com#34]
### Use Case

Partners looking to utilize the service would like custom branding, pre-populated form letters, etc. The user experience flow is a fair bit different than the standard person coming into the site. Users with the partner flow will have a referral link that can be referenced.

=============

- [x] Create issue boxes
    - [x] Add option to add to "pre populated" boxes (add to letter model) #45 
    - [x] Populate a set of boxes based on letters, instead of letter generation (add to org preferences) #46 
    - [x] Add option to "suggest reps" to letters, which will auto-select reps to send the letter to (add to letter model) #46 
    - [x] Encourage edit a letter #39

- [x] Upgrades to the organization models #42 
    - [x] Allow organizations to upload logos for landing page (add to org model) #41
    - [x] Allow organizations to customize copy for landing page (add to org model) #41
